language: java
jdk:
- oraclejdk8
#- openjdk8

env:
  global:
    - secure: "C4YaJ5XHeKKYzkkYEEpd4u5vifxSoxuINhNGTj+ZTyjTvQ4SHldIQaNZM9F//4sFGAH6tAv3PlQtFBXLPYxu6YA9rqQ1pUdn7B9nOcYVJAbigCeqt/OXs+qjakOMsCfZ1YJOfuxhD1THclPenc8eqhtfG5ywJxFoFDBVN4RHonNxoSxp0ff5sC6Nv69nSFnQl96sEJ2hEU/SBkwUbgp6W5FaAW1KAXD1r2TMtxMKIUQDPrL1C2fGrDKZPXEPfgYo1677RjPRSitolkWH/zUwym2qxARvGFMVewDUDu1VM5CM6iyUehryQblTJpkIugFuhwUpw4uagDRGyyN9VYvHNwvkKvifiJdLrWbAzq7p7JPcrP/pl3blS2JRDew02Kc5iI09KWmtUw+bp8p2yqsHnQPlMAcUWJ1Hx7wigybBb761b2NwirbvfCwSer2s7dzItP9eXbRPPB9CJCjP+hcy4bjgLStBN0rS7yYKQemRrLTeYvdrkurSXMBfB+uABllz4+KPUJaiAu/0wkn0+RjvYZKRUu1y11avCBYtvnvAaHtPA3+/hiSZsdByT+Lm72uW4OWu0a7A7gBTnfDIKeVlqtKowGHsu6gOY7DENZuojPaFU4nyR/+8nijPedJfVT0iz89qucfFzalLOyeVlgfh56vcXUmsDXQs1loKfAA/NOY="
    - secure: "UvTwhsngyDnXkNVddta87pNFp2rl4GXqTb51MuFX101+zLipDMHbQK3qveXhrHamdmTQPt6V7WPxvcHCQN0KCYL9fHL0tD4Gop8ld0oPK5ZY7fEE4s5iQin466m+7nyQKgbdPze+VYxB/Ma0IhYJ2XWB+dHSq6f2ouXX6Cd+k002hHXlr16kno7/Bov2QvgN5PlYlkbDZh7z5poBWzk1EKDCoaOx+NnVKQ9rFJDQR5pyDxAb44y1z2GQaSMhT3zx+CsUr2FqssXK3E9MBtnnd5an0xlwmdlpkG4Q9Wg8Hq3XYYnC0jpzPy1Pfo2w2zHfMmUxH6gmIGl/pgGDN4ohihb80XcTSOhZe2AZX2ac1cdSDNFRLKUxAaDP44iVqBefQyFLojQal4wnIxOvs5WKOsBtK63BfJFiJfK0uUdcHngP8HqnfbyN1Zms48VUqsjVJu6kse++mBsCigWcEIOqBdfEMaZpW051YmXq+UbcCfDA/gPKGbhzMpJVxg1PFvs992x80oilIjRIdRZwnmu06Ab79YD32I+EsOoSshd8XikqpLcizTW3xNmNKSU3olu06WBUfTtr2fa90uxomO/y7aRgAKJKg5a77oQY7xbEY3SgLq1xbt1NzzUeZt7ujiScwzBbcZKKAGBe9ZxlJbHT2lCI2YSsI9XScdVo4OAp0qE="
    - secure: "A4JChKWQuAP4YQ9qWwuGLjw3MWrx5DCAdVO2NxB4qcLv15DM7X+CXAMf8jrqboa8ulsKSXWk5Xu1IYGQ/6tWYwHrwx1ns4dOelstz5sQIAK+CDcRnwY23ay1Q9cjZeUqkO+g+9WQX+fPhJW3t2S0dw2kcbppbD8BiguOgC6DRU4RxkwsRD8nyTiJZcbDOuRAB/x1ZfcXyG4jaaEuj9a/MaEUNaJoeK8YOZLFmLEOfCQk/e2dUgqFSHZUri3/g1D997WI72NsLV1dxjUTdrCiupN1wwoDhLYmWETXObPVPhtPIMfgi3R+aUY9eE2jSSR4LKQraxjCdWpv65Ja4jCYTBOzwLgdwJKDKIBX4HOh+o+3oXrA3OATG0LEoDb7+8EMQeIwTPyKTPvwhKq3aZO8riZvmcBPLee/YaUq74RsrN/ddTIXZBeeQG79M5K2XcSpEzZBJHuHeJemfK1iE69h4DSJdOftGgGvXOFXYQbzHuIIPtGdZPUkM6xr/r2K2NCFA8KdLLdfP2kTNxPBJE/clGxgFRuLkEp9uRuHqn14mmVZRnfQugHIT0Vqh7+ldZjfD8fk9FHClo8yEIpbl9sx68v1kIoPsc+8RGgj8wEQwgjVupynYHeiSlinyZEhGDSjF0oEzv5deCDJOmPyKX4xSG63Sga8BK4nPmHQl5eQvSo="
    - secure: "gNqWSA0J1FTHcAAIlO6FDPGl/CgVOwPGWRrpvpPjTqmsoQVRqSJf5npSeycjz6MeAMbk7Syx3ArS9feIg7CqA/LPVn010Sez4rh09iMhqSW6VNOtAP94hVpeLogYRJSmbdZxXKB2149wDFEf+6/dUW0veDVms28MyEaH6PigFTIy+J4KJoejGexvdQ/N3hTOoDBLmW+wy0K2fQ/ySbkV4Q1CHmpgfoXR7CHXE7fqetnQenuyxQ2DezyHAHzVyxHK7h4fzTowb4Er11/a02WanIBqqgQy79TbinXSDshMsCqjh0A45zERBSqJyFUoXgYmCdJ7u+WQfCoh9ZglacZiB5sGdG2XVt1aUZmAmjPeez4Nj5Hq8BT2EOMcCtZGmF/ww60l9P3Z/jY93awIazOGFROy2HYdyi7PkPSEvPu3vLc7imxhD3vVG9VKM79vR1FvYLEJU63vfge4icXjU69/1FEE7FGAUtOyeGQePM1FWnF6aI6XSs02XsL8RT/VudKYS8+SuROtXIa5ZOtwdGa6az7fBn7OiJ64SoIA5d64u0DdIct1mkKEGHwLOxnqCeOylyF0Gz1cAHAU82bbU9AUN1s+LIEfem04NL2be77hvHB3PNoQS1fSLd06CwX207GBSIWPM3LvNsFqSc9pYHDkbtNgvjgzbawRIDD8QuOVruc="

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2
    
before_install:
- ./build-env/install-etcd.sh "$HOME/etcd"
- export PATH="$HOME/etcd:$PATH"


after_success: ./cd/deploy.sh